- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    pacman: name={{item}}
    with_items:
      - htop
      - tmux
      - zsh
      - git
      - python
      - vim
      - iw
